services:

  redis:
    image: redis:alpine3.16
    container_name: redis
    networks:
      - blogger
    ports:
      - 6379:6379

  authserver:
    image: blogger-authserver
    container_name: authserver
    networks:
      - blogger
    ports:
      - 44312:443
      - 18080:80

networks:
  blogger:
    driver: bridge